wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1642315235
    t:
      1:
      - 3
      - 5
      2:
      - 3
      - 5
      4: 3.8.10
      5: 0.12.9
      8:
      - 5
